### ISSUE TITLE
Fix typos in the README.md files

### ISSUE THREAD

**Issue by devRawnie** [antrikshmisri/checkpoint#32]
There are small typos in multiple places in the markdown files. Those need to be identified and fixed.

**Comment by salma77** [comment]
@devRawnie can I take this issue please?

**Comment by devRawnie** [comment]
Sure, Assigning this to you


> @devRawnie can I take this issue please?

**Comment by salma77** [comment]
> Sure, Assigning this to you. Could you also make a list of all the places where such fixing is required, here in the comments only!!
> 
> > @devRawnie can I take this issue please?

sure, the main readme file is the only one with typos, it has 7 typos; 2 typos in line 45, 2 typos in line 47, 2 in line 50, and 1 typo in line 117

**Comment by devRawnie** [comment]
Okay. Please go ahead with the changes
