### ISSUE TITLE
Hindi Readme for multilinguals

### ISSUE THREAD

**Issue by A91y** [antrikshmisri/checkpoint#43]
New Readme can be written in Hindi to help multilinguals.

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by antrikshmisri** [comment]
Hey @A91y, thanks for creating the issue. As of now, there is no plan to add `README` in a different language. Currently, it would be better to improve the `README` and then add translations. Thanks!
